[package]
name = "databases"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.23", features = ["rustls-tls"] }
tokio = { version = "1.35.1", features = ["full"] }
flate2 = { version = "1.0.28" }
tar = { version = "0.4.40" }